[package]
name = "fapra"
version = "0.1.0"
authors = ["Florian Barth <florianbarth@gmx.de>"]

[dependencies]
osmpbfreader = "*"
heapsize_derive = "*"
heapsize = "*"
rocket = "*"
rocket_codegen = "*"
ordered-float = "*"
geojson = "*"
serde_json = "*"

[profile.release]
debug = true
